PRODUCT_SEEDS = [
    {"id": 1, "nama": "Beras Fortune 5 KG", "harga": 96000, "kategori": "Bahan Pokok", "img": "1.webp", "desc": "Beras pulen kualitas premium, cocok untuk keluarga besar."},
    {"id": 2, "nama": "GULAKU 1KG", "harga": 18000, "kategori": "Bahan Pokok", "img": "2.jpg", "desc": "Gula pasir putih berkualitas, manis alami."},
    {"id": 3, "nama": "Gula Halus Rose Brand 500 GR", "harga": 14000, "kategori": "Bahan Pokok", "img": "3.jpg", "desc": "Gula halus lembut untuk kue dan minuman."},
    {"id": 4, "nama": "Tepung Segitiga Biru 1KG", "harga": 16000, "kategori": "Bahan Pokok", "img": "4.jpg", "desc": "Tepung serbaguna untuk gorengan dan baking."},
    {"id": 5, "nama": "Indomie Goreng 1 dus", "harga": 137500, "kategori": "Makanan Instan", "img": "5.jpg", "desc": "Indomie goreng favorit keluarga, isi 40 bungkus."},
    {"id": 6, "nama": "Indomie Soto Mie 1 dus", "harga": 140500, "kategori": "Makanan Instan", "img": "6.jpg", "desc": "Rasa kuah soto yang gurih dan segar."},
    {"id": 7, "nama": "Indomie Ayam Bawang 1 dus", "harga": 125000, "kategori": "Makanan Instan", "img": "7.jpg", "desc": "Cita rasa bawang yang harum dan khas."},
    {"id": 8, "nama": "Mie Sedap Goreng 1 dus", "harga": 140000, "kategori": "Makanan Instan", "img": "8.jpg", "desc": "Mie goreng dengan bumbu kaya rempah."},
    {"id": 9, "nama": "Indomie Ayam Geprek 1 dus", "harga": 143500, "kategori": "Makanan Instan", "img": "9.jpg", "desc": "Pedas nikmat ala ayam geprek."},
    {"id": 10, "nama": "Garam Kapal 250 Gr", "harga": 3000, "kategori": "Bumbu Dapur", "img": "10.jpg", "desc": "Garam meja halus untuk masakan sehari-hari."},
    {"id": 11, "nama": "Masako Ayam 11 Gr (6 Sachet)", "harga": 13000, "kategori": "Bumbu Dapur", "img": "11.jpg", "desc": "Penyedap rasa ayam praktis."},
    {"id": 12, "nama": "Royco Sapi (12 Sachet)", "harga": 15000, "kategori": "Bumbu Dapur", "img": "12.jpg", "desc": "Bumbu penyedap sapi berkualitas."},
    {"id": 13, "nama": "Teh Kotak Jasmine 200 Ml", "harga": 4000, "kategori": "Minuman", "img": "13.jpg", "desc": "Teh melati segar dalam kemasan kotak."},
    {"id": 14, "nama": "Teh Pucuk Harum 350 Ml", "harga": 3500, "kategori": "Minuman", "img": "14.jpg", "desc": "Teh hijau pucuk terbaik, segar dan sehat."},
    {"id": 15, "nama": "FRUIT TEA Apple 350ML", "harga": 4000, "kategori": "Minuman", "img": "15.jpg", "desc": "Teh rasa apel yang menyegarkan."},
    {"id": 16, "nama": "POTABEE BARBEQUE 68 GR", "harga": 28000, "kategori": "Snack", "img": "16.webp", "desc": "Keripik kentang rasa BBQ yang renyah."},
    {"id": 17, "nama": "KitKat 45gr", "harga": 11000, "kategori": "Snack", "img": "17.jpg", "desc": "Coklat renyah berlapis wafer."},
    {"id": 18, "nama": "CHEETOS Puffs 60 gr", "harga": 21000, "kategori": "Snack", "img": "18.jpg", "desc": "Snack keju yang ringan dan renyah."},
    {"id": 19, "nama": "Head & Shoulder 350ml", "harga": 87000, "kategori": "Kebutuhan Mandi", "img": "19.jpg", "desc": "Shampoo anti ketombe cool menthol."},
    {"id": 20, "nama": "SUNLIGHT BOTOL 750 ML", "harga": 49000, "kategori": "Kebutuhan Cuci", "img": "20.jpg", "desc": "Sabun cuci piring pemotong lemak."},
    {"id": 21, "nama": "Pepsodent Action 123 180 GR", "harga": 27000, "kategori": "Kebutuhan Mandi", "img": "21.jpg", "desc": "Sikat gigi 3 arah bersih maksimal."},
    {"id": 22, "nama": "SO GOOD TELUR OMEGA3 10S", "harga": 34000, "kategori": "Produk Segar", "img": "22.webp", "desc": "Telur kaya omega untuk tumbuh kembang."},
    {"id": 23, "nama": "Smoked Beef Metzger 100gr", "harga": 23000, "kategori": "Produk Segar", "img": "23.webp", "desc": "Daging sapi asap halal siap saji."},
    {"id": 24, "nama": "Snack Buah Strawberry Kering Freeze Dried 1 Kg", "harga": 66000, "kategori": "Snack", "img": "24.jpg", "desc": "Snack buah strawberry kering sehat tanpa pengawet."},
    {"id": 25, "nama": "Minyak Goreng Bimoli 2 L", "harga": 42000, "kategori": "Bahan Pokok", "img": "25.jpg", "desc": "Minyak goreng berkualitas untuk masak sehari-hari."},
    {"id": 26, "nama": "Sarden King 155 gr", "harga": 18000, "kategori": "Makanan Instan", "img": "26.jpg", "desc": "Ikan sarden dalam saus tomat, praktis dan bergizi."},
]
